Repository dharmaprotocol/dharma.js, pull requests merged in 2018-04, with the labels that each got.

#51 Test suite for `CollateralizedLoanTerms` class
  __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
Labels: test

#52 Test suite for `CollateralizedSimpleInterestLoanAdapter`
  __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
  src/adapters/collateralized_simple_interest_loan_adapter.ts
  src/adapters/index.ts
Labels: test

#62 fix: rename collateralizedAdapter to collateralizerAdapter
  __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
  src/adapters/collateralized_simple_interest_loan_adapter.ts
Labels: needs-review

#60 feat: add wrapper for collateralizer
  src/wrappers/contract_wrappers/collateralizer_wrapper.ts
  src/wrappers/index.ts
Labels: needs-review

#63 Add loadCollateralizerAsync to contracts api
  src/apis/contracts_api.ts
  src/types/dharma_config.ts
  src/wrappers/index.ts
  utils/constants.ts
Labels: needs-review

#70 Scaffolding for `DebtTokenAPI` test suite
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/scenarios/balance_of.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  src/apis/index.ts
  utils/constants.ts
Labels: test

#72 Add add'l scenarios for testing `balanceOf` method on Debt Token API
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/scenarios/balance_of.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
Labels: needs-review, test

#79 Test suite for `exists` method on the Debt Token API
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/runners/exists.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/scenarios/exists.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
Labels: test

#82 Test suite for `approve`
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/runners/approve.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/scenarios/approve.ts
  __test__/integration/debt_token_api/scenarios/exists.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  src/apis/debt_token_api.ts
  src/invariants/debt_token.ts
Labels: test

#84 Add ERC721 Receiver Wrappers
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/runners/balance_of.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/runners/transfer_from.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  __test__/integration/debt_token_api/scenarios/successful_transfer_from.ts
  __test__/integration/debt_token_api/scenarios/unsuccessful_transfer_from.ts
  package.json
  src/apis/debt_token_api.ts
  src/invariants/debt_token.ts
  src/invariants/schema.ts
  src/schemas/basic_type_schemas.ts
  src/schemas/schemas.ts
  src/types/transaction_options.ts
  src/wrappers/contract_wrappers/base_contract_wrapper.ts
  src/wrappers/contract_wrappers/debt_token_wrapper.ts
  src/wrappers/contract_wrappers/erc721_receiver_wrapper.ts
  src/wrappers/contract_wrappers/mock_erc721_receiver_wrapper.ts
  src/wrappers/index.ts
  utils/transaction_utils.ts
  yarn.lock
Labels: transfer-from-tests

#90 Test suite for `getApproved`
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/runners/get_approved.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/scenarios/get_approved.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/orders.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  yarn.lock
Labels: test

#67 feat: add seizeCollateral and returnCollateral methods
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/order_api/order_api.spec.ts
  __test__/integration/order_api/scenarios/invalid_orders.ts
  __test__/integration/servicing_api/runners/get_debts.ts
  __test__/integration/servicing_api/runners/get_expected_value_repaid.ts
  __test__/integration/servicing_api/runners/get_investments.ts
  __test__/integration/servicing_api/runners/get_repayment_schedule.ts
  __test__/integration/servicing_api/runners/get_value_repaid.ts
  __test__/integration/servicing_api/runners/make_repayment.ts
  __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
  __test__/unit/blockchain_api/scenarios/error_scenarios.ts
  src/adapters/collateralized_simple_interest_loan_adapter.ts
  src/apis/adapters_api.ts
  src/index.ts
  src/wrappers/contract_wrappers/debt_kernel_wrapper.ts
  utils/web3_utils.ts
Labels: reviewed

#94 Test suite for `setApprovalForAll`
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/runners/set_approval_for_all.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  __test__/integration/debt_token_api/scenarios/set_approval_for_all.ts
  src/apis/debt_token_api.ts
Labels: reviewed, test

#95 Test suite for `isApprovedForAll`
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/debt_token_scenario_runner.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/runners/is_approved_for_all.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/is_approved_for_all.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  src/apis/debt_token_api.ts
Labels: reviewed, test

#81 returnCollateral adapter integration tests
  .gitignore
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/collateralized_simple_interest_loan_adapter.spec.ts
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/runners/index.ts
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/runners/return_collateral_runner.ts
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/scenarios/index.ts
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/scenarios/successful_return_collateral_scenarios.ts
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/scenarios/unsuccessful_return_collateral_scenarios.ts
  __test__/unit/blockchain_api/error_scenario_runner.ts
  src/adapters/collateralized_simple_interest_loan_adapter.ts
  src/schemas/custom_formats.ts
  src/wrappers/contract_wrappers/debt_kernel_wrapper.ts
Labels: reviewed

#97 Add add'l validations to Debt Token API methods
  src/apis/debt_token_api.ts
Labels: reviewed

#101 Add error scenarios for `getApproved`
  __test__/integration/debt_token_api/debt_token_api.spec.ts
  __test__/integration/debt_token_api/runners/get_approved.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/scenarios/get_approved.ts
  __test__/integration/debt_token_api/scenarios/index.ts
  __test__/integration/debt_token_api/scenarios/orders.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
Labels: reviewed

#99 refactor: import bignumber from utils
  __test__/integration/adapters/collateralized_simple_interest_loan_adapter/scenarios/index.ts
  __test__/integration/debt_token_api/runners/approve.ts
  __test__/integration/debt_token_api/runners/exists.ts
  __test__/integration/debt_token_api/runners/index.ts
  __test__/integration/debt_token_api/runners/owner_of.ts
  __test__/integration/debt_token_api/runners/transfer_base.ts
  __test__/integration/debt_token_api/scenarios/orders.ts
  __test__/integration/debt_token_api/scenarios/scenarios.ts
  __test__/integration/debt_token_api/scenarios/transfer.ts
  __test__/integration/debt_token_api/scenarios/transfer_from.ts
  __test__/integration/order_api/order_scenario_runner.ts
  __test__/integration/order_api/scenarios/index.ts
  __test__/integration/order_api/scenarios/invalid_issuance_cancellations.ts
  __test__/integration/order_api/scenarios/invalid_order_cancellations.ts
  __test__/integration/order_api/scenarios/invalid_orders.ts
  __test__/integration/order_api/scenarios/nonconsensual_orders.ts
  __test__/integration/order_api/scenarios/successful_order_generation.ts
  __test__/integration/order_api/scenarios/successful_unpack_terms.ts
  __test__/integration/order_api/scenarios/unsuccessful_order_generation.ts
  __test__/integration/order_api/scenarios/valid_issuance_cancellations.ts
  __test__/integration/order_api/scenarios/valid_order_cancellations.ts
  __test__/integration/order_api/scenarios/valid_orders.ts
  __test__/integration/servicing_api/runners/get_debts.ts
  __test__/integration/servicing_api/runners/get_expected_value_repaid.ts
  __test__/integration/servicing_api/runners/get_investments.ts
  __test__/integration/servicing_api/runners/get_repayment_schedule.ts
  __test__/integration/servicing_api/runners/get_value_repaid.ts
  __test__/integration/servicing_api/runners/make_repayment.ts
  __test__/integration/servicing_api/scenarios/get_expected_value_repaid.ts
  __test__/integration/servicing_api/scenarios/get_repayment_schedule.ts
  __test__/integration/servicing_api/scenarios/index.ts
  __test__/integration/servicing_api/scenarios/invalid_make_repayment.ts
  __test__/integration/token_api.spec.ts
  __test__/unit/blockchain_api/error_scenario_runner.ts
  __test__/unit/blockchain_api/scenarios/error_scenarios.ts
  __test__/unit/blockchain_api/scenarios/invalid_orders.ts
  __test__/unit/blockchain_api/scenarios/valid_orders.ts
  src/apis/contracts_api.ts
  src/apis/debt_token_api.ts
  src/apis/servicing_api.ts
  src/apis/token_api.ts
  src/invariants/debt_agreement.ts
  src/invariants/debt_token.ts
  src/invariants/token.ts
  src/schemas/custom_formats.ts
  src/wrappers/contract_wrappers/collateralized_simple_interest_terms_contract_wrapper.ts
  src/wrappers/contract_wrappers/collateralizer_wrapper.ts
  src/wrappers/contract_wrappers/token_registry_wrapper.ts
Labels: reviewed

#109 fix: remove non-relative imports
  src/wrappers/contract_wrappers/base_contract_wrapper.ts
  src/wrappers/contract_wrappers/debt_kernel_wrapper.ts
Labels: needs-review

#126 build: bump contracts and wrapper
  package.json
  src/wrappers/contract_wrappers/token_registry_wrapper.ts
Labels: reviewed

#125 feat: return more info in tokens list
  __test__/integration/token_api.spec.ts
  __test__/utils/utils.ts
  src/apis/token_api.ts
Labels: reviewed

#128 Build: Bump charta version
  __test__/unit/adapters/simple_interest_loan_adapter.spec.ts
  package.json
  src/adapters/simple_interest_loan_adapter.ts
  yarn.lock
Labels: WIP

#135 feat: add validate function for adapters
  __test__/integration/order_api/order_scenario_runner.ts
  __test__/unit/adapters/collateralized_simple_interest_loan_adapter.spec.ts
  src/adapters/adapter.ts
  src/adapters/collateralized_simple_interest_loan_adapter.ts
  src/adapters/simple_interest_loan_adapter.ts
  src/adapters/simple_interest_loan_terms.ts
  src/apis/adapters_api.ts
  src/apis/contracts_api.ts
  src/apis/order_api.ts
  src/invariants/index.ts
  src/invariants/order.ts
Labels: needs-review
